// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9URoZiMbn-ZMbcvmW0kTLNaqs2t5f6M8',
    appId: '1:877718439659:web:a85d274d6c1c4d8ab0e0ae',
    messagingSenderId: '877718439659',
    projectId: 'sajilobus-80d0d',
    authDomain: 'sajilobus-80d0d.firebaseapp.com',
    storageBucket: 'sajilobus-80d0d.firebasestorage.app',
    measurementId: 'G-26BNJNVKDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUooWcXyhMiWJIZ7Jcg7UNPDjLYlP4Z_I',
    appId: '1:877718439659:android:563fcd013b7ba3fdb0e0ae',
    messagingSenderId: '877718439659',
    projectId: 'sajilobus-80d0d',
    storageBucket: 'sajilobus-80d0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjW2XOXkSRhak3P4v2UXn-lv2exXN4_gg',
    appId: '1:877718439659:ios:e1e0b532ffe1e811b0e0ae',
    messagingSenderId: '877718439659',
    projectId: 'sajilobus-80d0d',
    storageBucket: 'sajilobus-80d0d.firebasestorage.app',
    iosBundleId: 'com.example.sajiloBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjW2XOXkSRhak3P4v2UXn-lv2exXN4_gg',
    appId: '1:877718439659:ios:e1e0b532ffe1e811b0e0ae',
    messagingSenderId: '877718439659',
    projectId: 'sajilobus-80d0d',
    storageBucket: 'sajilobus-80d0d.firebasestorage.app',
    iosBundleId: 'com.example.sajiloBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9URoZiMbn-ZMbcvmW0kTLNaqs2t5f6M8',
    appId: '1:877718439659:web:8914c8f8c4cd7348b0e0ae',
    messagingSenderId: '877718439659',
    projectId: 'sajilobus-80d0d',
    authDomain: 'sajilobus-80d0d.firebaseapp.com',
    storageBucket: 'sajilobus-80d0d.firebasestorage.app',
    measurementId: 'G-GRVE7H5XH4',
  );
}
